apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:LZLA//hARuw9sm2Nfd1PYZvxkGVxfOCxhLKe29lQP0S7q1JQ7e7C0w==,iv:9rh2c8kbg5g8s6xpo/YRI9T89twB9mgYbuwJt/SBCTA=,tag:4z52/AJKH0Qx7D8awKnBhg==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0c0JHVmZKa2dXRlRJd0dB
            Q05NN1VNblZUcEF6b29kR3d2eFA5bDlTQ2tvCi9EMkhrK1pDaUNDOVFTeGdsRXoz
            RjlycWxvMTJ5ZUJIaHVhdk1lRnpkdlkKLS0tIHp1Z1dLS2xtaUI1SXRiMUltT0dz
            MVU4RHh1SE1Nc1JCaDU3QkZXak9SV00KqDqOHSZV733k0sh2PFXxgZejpHGKfPx9
            ndDcbUpCLzdWjko06XY5ttkEnviCLIM69P2JgIn1F31HdZ+0ysdAJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T13:32:44Z"
    mac: ENC[AES256_GCM,data:bqAWLmWIXhAOPcQ9k9+cjzYpr/eqeYAaGsDFhuhGgcKp9ED3Vom/TYRUsQwhniicazt+iFaZDnP5H+Yu5r2NIY/8G4BDcjnivSf2tx21/yHnUv7oWfiuh6DUUFvszrUFHHY59vLLt4QwM0QxKu4oHxZRIwzVYbkXKLhW7ZYwgJ4=,iv:N61xikBjd27SQINWanBdwp5s4L35AsdGPDOv0hPhUsc=,tag:iPNydVcQcggiG4P8ZqHpAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
