apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Homelab
    theme: dark
    color: slate
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/zarnautovic 
  services.yaml: |
    - Infrastructure:
        - Proxmox:
            icon: proxmox.svg
            href: "https://192.168.1.10:8006"
            widget:
              type: proxmox
              url: "https://192.168.1.10:8006"
              username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
              password: "{{HOMEPAGE_VAR_PROXMOX_KEY}}"
        - Authentik:
            icon: authentik.svg
            href: "https://authentik.zlaya.tech"
            widget:
              type: authentik
              url: http://authentik-server.authentik.svc.cluster.local
              key: "{{HOMEPAGE_VAR_AUTHENTIK_KEY}}"
              version: 2
  widgets.yaml: |
    - greeting:
        text: Welcome
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: homelab
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: true
  docker.yaml: |
    {}
  custom.css: ""
  custom.js: ""
  proxmox.yaml: ""
