apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
stringData:
    HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:jJHYYXmg+raOn3M44BkHiw==,iv:yrDmXYW4twhJwutMvVdi8vaJrk9iohHY9GHe11H8KN4=,tag:WY0BCTH+XCo10hQQi/tn7A==,type:str]
    HOMEPAGE_VAR_PROXMOX_KEY: ENC[AES256_GCM,data:UG4gcQgN75PMny6JlPkxcCRqRysD6Etu0vFnzZvvUUQtbJzD,iv:1MEDywOwBifabu3skrxZ3eQNGIGm9g+qkS4SONnadak=,tag:CioA31SjY56RI8Mby5lccw==,type:str]
    HOMEPAGE_VAR_AUTHENTIK_KEY: ENC[AES256_GCM,data:F0nWi00PaldjxLxBpCmguEmWBlTYG5502omnl84fMoCta0HgoWi/hnPUVuyTkiHnHImqz67nL4UnYznJ,iv:AXl329V9rRZrISUMt7ff8AJB/QGeqsvoDeYIKHSLTII=,tag:24Aty5CVEBy0P4hpnkQMUg==,type:str]
    HOMEPAGE_VAR_TRUENAS_KEY: ENC[AES256_GCM,data:u/sucokkoyFekkdQp9nFYTJUDbSbjKSV1OI3kp+L4EK0tp6pFB9ockH3mshz65zgAquHiMixsbisquD/UHKdvph7,iv:rysJh9Xa2v/Px1uidN9+8rhekMgpy5MxB359UQ+QXJw=,tag:B7VVqFaGKBvKDXIc0URHRw==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaUxBNFppL3JhNHQvMVQw
            Qis4cUp1L1lnbFRkYy9haVUvOGNLZDFJbkNVCjAyVXlMdk5md01COHhvUEFKSGtl
            UDJ2Q3dkVURxWE1uNVdUSTRPdVphblkKLS0tIHpsdnlMYWk3WXZxcFhuVjBMYmYr
            QU05akZ4cktzczBCcUwrcDNIbkI3ajQKSBR0E2x0UwM0dfbiEaNFqHYDtPHPrpCB
            xhl7K6fT0LV+wve4S9o0jzdaAFAXSjRU53cUoZ525CQA7GlaZTSkxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T10:41:16Z"
    mac: ENC[AES256_GCM,data:oDm6bNOJVHZn2T7e2HWtsxKPTB3NtlKq+ekhOnIt2elVSI0zJnunhMv/5ZoJMsM8p52r+X34STViT2mbyWHNbgPO1X+NBHcJnTgexDTXgbwr0yB4wvvoqihlkPEvvA9kkJLW67zBz55mtLkRO3N8dxl+IaOSRo3Ddo4mI172OuI=,iv:aEUN4WQT5pWv+yQVOSyt/mHLyowCiiS792ik8fBHRFk=,tag:NdavOiOzVHOLOOLCWy7aPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
