apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
stringData:
    HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:jJHYYXmg+raOn3M44BkHiw==,iv:yrDmXYW4twhJwutMvVdi8vaJrk9iohHY9GHe11H8KN4=,tag:WY0BCTH+XCo10hQQi/tn7A==,type:str]
    HOMEPAGE_VAR_PROXMOX_KEY: ENC[AES256_GCM,data:UG4gcQgN75PMny6JlPkxcCRqRysD6Etu0vFnzZvvUUQtbJzD,iv:1MEDywOwBifabu3skrxZ3eQNGIGm9g+qkS4SONnadak=,tag:CioA31SjY56RI8Mby5lccw==,type:str]
    HOMEPAGE_VAR_AUTHENTIK_KEY: ENC[AES256_GCM,data:F0nWi00PaldjxLxBpCmguEmWBlTYG5502omnl84fMoCta0HgoWi/hnPUVuyTkiHnHImqz67nL4UnYznJ,iv:AXl329V9rRZrISUMt7ff8AJB/QGeqsvoDeYIKHSLTII=,tag:24Aty5CVEBy0P4hpnkQMUg==,type:str]
    HOMEPAGE_VAR_TRUENAS_KEY: ENC[AES256_GCM,data:u/sucokkoyFekkdQp9nFYTJUDbSbjKSV1OI3kp+L4EK0tp6pFB9ockH3mshz65zgAquHiMixsbisquD/UHKdvph7,iv:rysJh9Xa2v/Px1uidN9+8rhekMgpy5MxB359UQ+QXJw=,tag:B7VVqFaGKBvKDXIc0URHRw==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:iTSaGCR/MtK/7QQO8Lm/blluw9szTTOqZVOo3qr5rgs=,iv:tNayv4wRTtR1Y9GyTkROgywb7fHnomFVRSuv6ExDcUo=,tag:SgYezbr51HdjqDNH24Tesg==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:l9x46JxqIaypNhyaPsO5kY7NjKe9qHDN/DHQds2bc0Y=,iv:zTERr0bpqBk9wrQY1a6lv7nHO5Wiq+U9wHfOa/W7i6Y=,tag:Ygod3ZtyajDa0CPClrp7CA==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:XFgrQYeB5FMjPw9kA6XZZdJTx8iE7jVOUZ7RGAS5tmA=,iv:YMm8gIKegnKsWUwXHKROQ83Rrbu7SmBZ3cUcZehkfmM=,tag:eK328S4jmZqPsKD6F1FVkQ==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:iqbUvEA=,iv:i27S65ybmwMUy8RwSSxb0fDp966FF90I1Q5q9PCNNYc=,tag:HOfzeThfBn/VrYADYOsOVw==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:0Cj96At21mPgqA==,iv:ynrkEYvl5/6skjOZdCwmsCgicRDLu1ln5NPspXOLpvg=,tag:HB+/HYYWQc1kabTNphgIcg==,type:str]
    HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:TDZiTmqXgn/NbvjhKBKr18msZLJZhI3yiHsurkRIw/w=,iv:kRaKUKWobziBqednrs+edQBa04TtnRoqeW5WWdBM1lk=,tag:HaUXJ2b252cblzGextpvvA==,type:str]
    HOMEPAGE_VAR_SEERR_KEY: ENC[AES256_GCM,data:CT74F1p059TUl0+P7dxhLNHQ4Q+R5UXo2F2XACozk0HiS35KZie4OHO+cgFAN7Ssfs3LL1wy+2CJMR52Iuo+z7mcZ6A=,iv:P+DebCA/m9DKkHwK/VDmIjkWrhaP6+qi5e04cZI+YsQ=,tag:UKzl4g4fMJZZv2J3T4GS6Q==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaUxBNFppL3JhNHQvMVQw
            Qis4cUp1L1lnbFRkYy9haVUvOGNLZDFJbkNVCjAyVXlMdk5md01COHhvUEFKSGtl
            UDJ2Q3dkVURxWE1uNVdUSTRPdVphblkKLS0tIHpsdnlMYWk3WXZxcFhuVjBMYmYr
            QU05akZ4cktzczBCcUwrcDNIbkI3ajQKSBR0E2x0UwM0dfbiEaNFqHYDtPHPrpCB
            xhl7K6fT0LV+wve4S9o0jzdaAFAXSjRU53cUoZ525CQA7GlaZTSkxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T23:58:40Z"
    mac: ENC[AES256_GCM,data:bbU88tlyDJwCWDS9ppDR5JycKfNsl0WkaIpc+aESFJk2CfVMXHGP/UjR9GbEuBKIe0yauK2BODCFwJ1I/2x87cJZ+8RoZ+0sYUdHgJe8YC8FYhDC6i6L+3eHV4SPQII/VgdKmVGeBrU/pBPOMz2DVpnHPrSyR7mb/iaj7zaYjXE=,iv:RTKDNnK+15U+BLXFVr/NX7ZNLunLguJjyKHRBqgnWJg=,tag:ZnMuD+3GSnx7DhwY5BaLBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
