apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
stringData:
    HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:8ilGMro17tktAnd8oP594EHy4YDe,iv:pGfJLkbcRDPpbQ/LU+HBO58hPm0pGYTusX+QTl+KIVU=,tag:JwjKLhAB+7Ar6ySUyIpnFA==,type:str]
    HOMEPAGE_VAR_PROXMOX_KEY: ENC[AES256_GCM,data:UG4gcQgN75PMny6JlPkxcCRqRysD6Etu0vFnzZvvUUQtbJzD,iv:1MEDywOwBifabu3skrxZ3eQNGIGm9g+qkS4SONnadak=,tag:CioA31SjY56RI8Mby5lccw==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaUxBNFppL3JhNHQvMVQw
            Qis4cUp1L1lnbFRkYy9haVUvOGNLZDFJbkNVCjAyVXlMdk5md01COHhvUEFKSGtl
            UDJ2Q3dkVURxWE1uNVdUSTRPdVphblkKLS0tIHpsdnlMYWk3WXZxcFhuVjBMYmYr
            QU05akZ4cktzczBCcUwrcDNIbkI3ajQKSBR0E2x0UwM0dfbiEaNFqHYDtPHPrpCB
            xhl7K6fT0LV+wve4S9o0jzdaAFAXSjRU53cUoZ525CQA7GlaZTSkxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T20:18:10Z"
    mac: ENC[AES256_GCM,data:ZtViM+lOe9+zckoTJ9g+hL2Lj4xxD2zBAd9CPX38rMYmR7KZpTjhYzMpOF1zTl0XdT1BrrmBr1gNmETvYK5J9s8J4kgjdl85v53PtBt8f/qBYuwnCWmo0IwREiXEUv6ZNcYiQg4TfHjurLGBA7Ylc1B/2nrEZwwqpMAmLzr04Rs=,iv:tmPAA6+NGnMVyiVBSyivefnyJ7z1uBOQ1NKWPA+J+v4=,tag:SyldAiZ3249OR+9IalWzzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
