apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
stringData:
    HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:jJHYYXmg+raOn3M44BkHiw==,iv:yrDmXYW4twhJwutMvVdi8vaJrk9iohHY9GHe11H8KN4=,tag:WY0BCTH+XCo10hQQi/tn7A==,type:str]
    HOMEPAGE_VAR_PROXMOX_KEY: ENC[AES256_GCM,data:UG4gcQgN75PMny6JlPkxcCRqRysD6Etu0vFnzZvvUUQtbJzD,iv:1MEDywOwBifabu3skrxZ3eQNGIGm9g+qkS4SONnadak=,tag:CioA31SjY56RI8Mby5lccw==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaUxBNFppL3JhNHQvMVQw
            Qis4cUp1L1lnbFRkYy9haVUvOGNLZDFJbkNVCjAyVXlMdk5md01COHhvUEFKSGtl
            UDJ2Q3dkVURxWE1uNVdUSTRPdVphblkKLS0tIHpsdnlMYWk3WXZxcFhuVjBMYmYr
            QU05akZ4cktzczBCcUwrcDNIbkI3ajQKSBR0E2x0UwM0dfbiEaNFqHYDtPHPrpCB
            xhl7K6fT0LV+wve4S9o0jzdaAFAXSjRU53cUoZ525CQA7GlaZTSkxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T20:26:13Z"
    mac: ENC[AES256_GCM,data:Jdl+SBbk1dlONM9JHhJlqkcoRWM+O6L/3mY4pqCqCU2pbCxwstJHcnTyqrGyO9E5sw7jeaAlDUIHN/l3Dx2V7R8AW2o8l2XAiZgrpuWPSbWfr+o4ngzT+4TCXT7uSoHoGNAWZWR5Cxb7nMeDRxUBLy3CWNOzcSfnMJmRIoGmlwk=,iv:u7qzeIO4RAOMsnARK7OnDxfvPJivsEePhfswQy1dTuo=,tag:dOoiX6ZeANkOHsyq79xTtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
