apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    secret_key: ENC[AES256_GCM,data:BmkG7QX9twVqas0LeZiRtX0AzN0hwfOctfcOsTkFQUThn1KEHfe6be8LTUpEBY8/,iv:PwxoajK3vA1R1s1oPI2BZjj+3pmug+/2gqE3kubNaWw=,tag:o0Vm/pUCd7Qn/tYYr+PdwQ==,type:str]
    postgresql_password: ENC[AES256_GCM,data:Q8G5jguwbO7uNckJDWMyp70SwBzJ0oKqnCr5qOB/GBE=,iv:YnTwGFYNgDhcg2hR9PvZwFgWgDwUmBjPBTISRdf3DU8=,tag:XkfT3CTmvMhAm/brZrT+dw==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFenZ6eHhwTEowcENwQmhu
            WFN2Q0FJa2pGSHdDbEQ1ak9lcGxMeldwYVgwCjYzOFJOOHYrSUp1NmcvVCt5L2gv
            V0RGWnh5aG9VRXN3YU9ySEorb1YxYjQKLS0tIDJKTXNtVk1FOW1lNER1OHNXRUNy
            Vlp0aUIxbGZEUWlCL1JQS0ZwVUNZSDgKNo9cfcdM15HFS58WOrXtpqF0dGmUFCj2
            XBGGtHjn2KlXDR/lBzCKLPTkW1dXuu3q/DH3IvErsQYVTE7KzCBpAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T22:12:43Z"
    mac: ENC[AES256_GCM,data:sXQKC0s1pU1X5U/qPcu1U0sLfXJznahXXlKJGsWpREKIOBG1hMQGv7DucXVQfVgw4i2egRLLRZX0CprmI9qzrm+NRYYhv+rL9xPJgfTGeFi6UoEMu32oXQ9BVupJViZtr5DH1GwbFB+Qh81mw3yuVw5mIwvpB5jn5yas+1Tc/ZI=,iv:6N4WQWlLUZiIk/L//AtXH9dsVVJ0FAALoiOtBhMeK1g=,tag:ok2AueQ5MVeKwrA60QbEUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
