apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-zlaya-tech-tls
  namespace: network
spec:
  secretName: wildcard-zlaya-tech-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.zlaya.tech"
  dnsNames:
    - "*.zlaya.tech"
    - "zlaya.tech"
