apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main
  namespace: network
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      port: 443
      protocol: HTTPS
      hostname: "*.zlaya.tech"
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-zlaya-tech-tls
            namespace: network
      allowedRoutes:
        namespaces:
          from: All
    - name: https-root
      port: 443
      protocol: HTTPS
      hostname: "zlaya.tech"
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-zlaya-tech-tls
            namespace: network
      allowedRoutes:
        namespaces:
          from: All
