apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flaresolverr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          env:
            - name: TZ
              value: Europe/Zagreb
            - name: LOG_LEVEL
              value: info
          ports:
            - name: http
              containerPort: 8191
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: prowlarr
spec:
  selector:
    app.kubernetes.io/name: flaresolverr
  ports:
    - name: http
      port: 8191
      targetPort: 8191
