apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seerr
  namespace: seerr
spec:
  parentRefs:
    - name: main
      namespace: network
  hostnames:
    - "seerr.zlaya.tech"
  rules:
    - backendRefs:
        - name: seerr
          port: 5055
