apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.101
    path: /mnt/media-pool/media-share/torrent
  claimRef:
    name: qbittorrent-downloads
    namespace: qbittorrent
