apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secrets
    namespace: qbittorrent
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:sIPEUg8yZbr8YToaNerZBK9049i6Nj1JSjNuPmcmrcE4TxHQfZ4RcMdiLdY=,iv:u6xNoWtgZGa64EsKhdL20wV74JtTpxdJ8FLlalQNIa0=,tag:vpGjdBThZzeJtTKttcTWyg==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSEJOTG5jTmhHU3F3QlIr
            Rjg5cXJudzJWbXcxYzZvNmxCbHlyODRkUUc4Cjljcjh0dktiek5KWnZKdFlkSGY4
            TU54aFBLL284dmZ5Q2o4Qk9CRHlpNUkKLS0tIHliczRVdUxNSHB4S29RSS81b2dl
            TGtldzJRM1NZb2dtc2hjeVlnT2FCaE0K317V/v4WqxbRuxABaMXO/Gnogs0mChey
            y3Ca9Vo0DbgAHB9I7R1DczGrmBQKAZTuWsHYmPLPXzbSBBrOchkECA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T12:18:51Z"
    mac: ENC[AES256_GCM,data:xyBLYnuKpkJNtnWt0Pp1ec0aRYlNEfasMPE+/NseVP88cSIbbphMoX7w09DRL0p3DF7YuLsvkurSacvuk8MbWvudhLSbTjQeVFOvwreZF7vE75LU0TGRFw4CmZlMj9XAEKjEo4h9hxYNo8tsgA7xLdt6F/cPmffY/lOXuKUaP+I=,iv:NfGJdebUYERBANeeUZPZC5lcVgSDpQYdeATmW3Brjz0=,tag:r/7ffRs7mU7TnHr/KVzhpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
