apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-media-nfs
spec:
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.101
    path: /mnt/media-pool/media-share
  claimRef:
    name: radarr-media
    namespace: radarr
